CREATE OR REPLACE FUNCTION F_GET_FWJZRKCOUNT(V_FWID VARCHAR2)
RETURN NUMBER
--查询房屋居住人口统计数量
AS
       V_RKZS     NUMBER;
       V_CZRKS    NUMBER;
       V_LDRKS    NUMBER;
       V_JWRKS    NUMBER;
       V_JZRKS    NUMBER;
       V_WLHRKS   NUMBER;
BEGIN
        --常住人口数
        SELECT COUNT(1) INTO V_CZRKS
        FROM T_LSGL_RK_CZRK CZRK INNER JOIN T_LSGL_RKFW_GL GL ON CZRK.RKFWGLID=GL.RKFWGLID
        WHERE (CZRK.ZXBS IS NULL OR CZRK.ZXBS='0') 
               AND GL.FWID=V_FWID;
         
        --流动人口数
        SELECT COUNT(1) INTO V_LDRKS
        FROM T_LSGL_RK_LDRKZZXX LK INNER JOIN T_LSGL_RKFW_GL GL ON LK.RKFWGLID=GL.RKFWGLID
        WHERE (LK.ZXBS IS NULL OR LK.ZXBS='0') 
               AND GL.FWID=V_FWID;
               
        --境外人口数
        SELECT COUNT(1) INTO V_JWRKS
        FROM T_LSGL_RK_JWRKXX JW INNER JOIN T_LSGL_RKFW_GL GL ON JW.RKFWGLID=GL.RKFWGLID
        WHERE (JW.ZXBS IS NULL OR JW.ZXBS='0') 
               AND GL.FWID=V_FWID;
         
        --寄住人口数
        SELECT COUNT(1) INTO V_JZRKS
			  FROM T_LSGL_RK_JZRKXX JZ  INNER JOIN T_LSGL_RKFW_GL GL ON JZ.RKFWGLID=GL.RKFWGLID
				WHERE (JZ.ZXBS IS NULL OR JZ.ZXBS='0') 
						   AND GL.FWID=V_FWID;
        
        --未落户人口数
        SELECT COUNT(1) INTO V_WLHRKS
			  FROM T_LSGL_RK_WLHCZHK WLH  INNER JOIN T_LSGL_RKFW_GL GL ON WLH.RKFWGLID=GL.RKFWGLID
				WHERE (WLH.ZXBS IS NULL OR WLH.ZXBS='0') 
						   AND GL.FWID=V_FWID;
         
        V_RKZS:= V_CZRKS +  V_LDRKS +   V_JWRKS +  V_JZRKS +  V_WLHRKS;
        RETURN V_RKZS;

END;
/