-- Add/modify columns 
alter table T_LSGL_FW_JBXX modify FRDBXM VARCHAR2(30);
-- Add comments to the columns 
comment on column T_LSGL_FW_JBXX.FRDBXM
  is '公有房屋法人代表姓名';

  
CREATE OR REPLACE FUNCTION F_GET_FW_MAXDJSJ(V_STID VARCHAR2,V_DYH VARCHAR2,V_LCH VARCHAR2,V_FJH VARCHAR2,V_FSDZ VARCHAR2)
return date
as
 V_MAXDJSJ DATE;
begin
    SELECT MAX(DJSJ) INTO V_MAXDJSJ
    FROM T_LSGL_FW_JBXX 
    WHERE DZID IN (
          SELECT DZID
          FROM T_COMMON_DZXX
          WHERE STID=V_STID
          AND DYH=V_DYH
          AND LCH=V_LCH
          AND FJH=V_FJH
          AND FSDZ=V_FSDZ
    );
    RETURN V_MAXDJSJ;
end;
/

CREATE OR REPLACE FUNCTION F_GET_ST_MAXDJSJ(V_STMC VARCHAR2,V_SQDM VARCHAR2,V_JLXDM VARCHAR2,V_MPH VARCHAR2,V_XQZ VARCHAR2,V_LDXZ VARCHAR2)
RETURN DATE
AS
   V_MAXDJSJ DATE;
BEGIN
    SELECT MAX(DJSJ) INTO V_MAXDJSJ
    FROM T_COMMON_STXX
    WHERE STMC=V_STMC
          AND SQDM=V_SQDM
          AND JLXDM=V_JLXDM
          AND MPH = V_MPH
          AND XQZ = V_XQZ
          AND LDXZ = V_LDXZ;
    RETURN V_MAXDJSJ;
END;
/