-- Create database link 
create public database link TO_199
  connect to CS_JZ_BB identified by "CS_JZ_bb_20140128"
  using '(DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.143.1.199)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SID = csjzbb)
    )
  )';



create or replace  view v_ajjbxxb  as
select 
ID  
ACTTIME  ,
ACTFLAG ,
ACTUSER  ,
ANJIANBIAOZHI ,
ANJIANBIANHAO ,
GONGANBIANHAO ,
WENSHUNIANFEN  ,
WENSHUBIANHAO ,
WENSHUWENHAO ,
ANYOU  ,
ANJIANMINGCHENG ,
ANJIANZHUANGTAI  ,
ANJIANLAIYUAN  ,
BAOANRIQI ,
ANJIANLEIBIE  ,
FUANLEIBIE ,
SHOULIRIQI ,
SHEMIBIAOZHI ,
LIANRIQI ,
LIANLEIXING  ,
LIANDANWEI  ,
POANRIQI  ,
POANLEIXING  ,
POANDANWEI ,
JIEANRIQI,
JIEANLEIXING  ,
BANANREN1ID ,
BANANREN2ID ,
BANANDANWEIID  ,
YIJIAOQIANID ,
FAANSHIJIANKAISHI  ,
FAANSHIJIANJIESHU ,
SHIFOUWEITUO ,
YUNXULIAN ,
ZHISHU ,
BYORDER ,
KPZT ,
MSCORE ,
ZXKP,
ZSCORE ,
XYRFLAG,
SHRFLAG ,
SCORE1  ,
SCORE2,
SCORE3  ,
FAANSHEQU  ,
CHEANRIQI ,
LSHJFLAG  ,
ZJFLAG  ,
BLFLAG ,
PGIS_X , 
PGIS_Y  , 
HH  ,
RBKSJ  ,
FARQ,
FARQ_SQ	,
FASJ_XS	,
BANANDANWEIID2	

 from cs_jz_zfba.t_ajjbxxb@to_199