CREATE OR REPLACE FUNCTION F_GET_DZMC_BYDWFWGLID(V_DWFWGLID VARCHAR2) RETURN VARCHAR2
--通过单位房屋关联获取地址名称
AS
       
       v_dzid     varchar2(30);
       V_DZMC     VARCHAR2(1000);
BEGIN
       BEGIN
           SELECT DZID into v_dzid FROM t_lsgl_dwfw_gl where DWFWGLID=V_DWFWGLID;
           SELECT f_get_dzmc(v_dzid) INTO V_DZMC FROM DUAL;
       EXCEPTION WHEN OTHERS THEN
             V_DZMC:='';
       END;
       RETURN V_DZMC;
END;
/


CREATE OR REPLACE FUNCTION F_GET_DW_DZMC(V_JGBH VARCHAR2) RETURN VARCHAR2
--通过单位信息地址名称通过机构编号
AS

       V_DZID     VARCHAR2(30);
       V_DZMC     VARCHAR2(1000);
       V_MAXDJSJ  DATE;               --最大登记时间
BEGIN
       BEGIN
       
           SELECT MAX(DJSJ) INTO V_MAXDJSJ FROM T_LSGL_DWFW_GL T WHERE JGBH=V_JGBH AND (ZXBS IS NULL OR ZXBS='0');
           
           SELECT DZID INTO V_DZID FROM T_LSGL_DWFW_GL WHERE JGBH=V_JGBH AND (ZXBS IS NULL OR ZXBS='0') AND DJSJ=V_MAXDJSJ;
           
           SELECT F_GET_DZMC(V_DZID) INTO V_DZMC FROM DUAL;
           
       EXCEPTION WHEN OTHERS THEN
             V_DZMC:='';
       END;
       RETURN V_DZMC;
END;
/

CREATE OR REPLACE FUNCTION F_GET_DZMC_BYRKFWGLID(V_RKFWGLID VARCHAR2) RETURN VARCHAR2
--通过地址ID获取地址名称
AS
       
       V_DZID     VARCHAR2(30);
       V_DZMC     VARCHAR2(1000);
       
BEGIN
       BEGIN
           SELECT DZID INTO V_DZID FROM T_LSGL_RKFW_GL WHERE RKFWGLID=V_RKFWGLID;
           SELECT F_GET_DZMC(V_DZID) INTO V_DZMC FROM DUAL;

       EXCEPTION WHEN OTHERS THEN
             V_DZMC:='';
       END;
       RETURN V_DZMC;
END;
/

CREATE OR REPLACE FUNCTION F_GET_DZMC_BYFWID(V_FWID VARCHAR2) RETURN VARCHAR2
--通过房屋ID获取地址名称
AS
       V_DZID     VARCHAR2(30);
       V_DZMC     VARCHAR2(1000);
       
BEGIN
       BEGIN
           SELECT DZID INTO V_DZID FROM T_LSGL_FW_JBXX WHERE FWID=V_FWID;
           SELECT F_GET_DZMC(V_DZID) INTO V_DZMC FROM DUAL;
       EXCEPTION WHEN OTHERS THEN
             V_DZMC:='';
       END;
        RETURN V_DZMC;
END;
/
