CREATE OR REPLACE VIEW V_LSGL_LDRK_FWGL AS
SELECT LK.*,FW.FWID,FW.DZID,FW.FWMC,dz.dzmc,fw.sfczw
FROM V_LSGL_RK_LDRK LK LEFT JOIN T_LSGL_RKFW_GL GL ON LK.RKFWGLID=GL.RKFWGLID
     LEFT JOIN T_LSGL_FW_JBXX FW ON FW.FWID=GL.FWID
      left join t_common_dzxx dz on dz.dzid=gl.dzid;
      
      CREATE OR REPLACE VIEW V_LSGL_JZRK_FWGL AS
SELECT JZ.*,FW.FWID,FW.DZID,FW.FWMC,dz.dzmc,fw.sfczw
        FROM V_LSGL_RK_JZRKXX JZ LEFT JOIN T_LSGL_RKFW_GL GL ON JZ.RKFWGLID=GL.RKFWGLID
           LEFT JOIN T_LSGL_FW_JBXX FW ON FW.FWID=GL.FWID
            left join t_common_dzxx dz on dz.dzid=gl.dzid;