-- Add/modify columns 
alter table T_KHKP_JCSJCJSLTJ add CZFWXCS number;
-- Add comments to the columns 
comment on column T_KHKP_JCSJCJSLTJ.CZFWXCS
  is '出租房屋巡查数量 (不计算在总是内)';

  
CREATE OR REPLACE PROCEDURE P_KHKP_EXECJCSJCJTJ(V_JSJD VARCHAR2,V_TJYF VARCHAR2)
--基础数据采集统计  按月统计，只计算社区
-- 参数说明：  V_JSJD  计算阶段 计算阶段1：1号到10号 2：1号到20号  3：1号到30号
AS
 
     CURSOR CUR_LIST IS
        SELECT ORGCODE,PARENT_CODE,ORGNAME
        FROM V_COMMON_ORGANIZATION
        WHERE LEVE='5' 
              AND PARENT_CODE IS NOT NULL
              AND ISYX='1' 
              AND ORGCODE LIKE '4301%';

  TYPE LISTTYPE IS TABLE OF CUR_LIST%ROWTYPE;
  LIST       LISTTYPE;
  V_ORGCODE  VARCHAR2(12);
  V_PARENTCODE  VARCHAR2(12);
  V_ORGNAME  VARCHAR2(120);
  V_RECORD   NUMBER;
  V_ERROR    VARCHAR2(4000);
  V_LEVE     NUMBER;
  V_JSKSSJ     DATE;   --计算开始时间
  V_JSJSSJ     DATE;   --计算结束时间
  V_JSKSSJ_1     VARCHAR2(14);   --计算开始时间
  V_JSJSSJ_1     VARCHAR2(14);   --计算结束时间
  V_JCSJZS     NUMBER;
  V_CZRKZS     NUMBER;
  V_JZRKZS     NUMBER;
  V_LDRKZS       NUMBER;
  V_LDRKYQS      NUMBER;
  V_WLHRKS       NUMBER;
  V_FWXXS        NUMBER;
  V_STXXS        NUMBER;
  V_DWXXS        NUMBER;
  V_CYRYS        NUMBER;
  V_CZFWS        NUMBER;
  V_CZFWXCS      NUMBER;
  V_JSJD_1 VARCHAR2(1);
  V_JWQFL       VARCHAR2(2); -- 警务区分类
BEGIN
   
   V_JSKSSJ_1:=TO_CHAR(SYSDATE-1,'YYYYMM')||'01000000';
   V_JSJSSJ_1:=TO_CHAR(SYSDATE-1,'YYYYMMDD')||'235959';
   
   V_JSKSSJ:=TO_DATE(TO_CHAR(SYSDATE-1,'YYYYMM')||'01000000','YYYYMMDDHH24MISS');
   V_JSJSSJ:=TO_DATE(TO_CHAR(SYSDATE-1,'YYYYMMDD')||'235959','YYYYMMDDHH24MISS');
   
   
   IF V_JSJD = '1' OR V_JSJD = '2' OR V_JSJD = '3' THEN
     V_JSJD_1 := V_JSJD;
   ELSE 
     V_JSJD_1 := V_JSJD;
   END IF;
    
   
   OPEN CUR_LIST;
   LOOP
      --先拿出游标中的 1000 条数据
    FETCH CUR_LIST BULK COLLECT
      INTO LIST LIMIT 100;
    EXIT WHEN LIST.COUNT = 0;
    --循环 当前的1000条数据
    FOR I IN LIST.FIRST .. LIST.LAST LOOP
        BEGIN
            SELECT
                   T.ORGCODE,
                   T.PARENT_CODE,
                   T.ORGJC,
                   T.LEVE,
                   (SELECT COUNT(1) FROM T_LSGL_RK_CZRK WHERE (ZXBS IS NULL OR ZXBS='0') AND CZSJ>=V_JSKSSJ AND CZSJ<=V_JSJSSJ AND CZDWDM=LIST(I).ORGCODE AND RKFWGLID IS NOT NULL) AS CZRKZS, --本月常住人口登记数量
                   (SELECT COUNT(1) FROM T_LSGL_RK_LDRKZZXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS LDRKS, --流动人口数
                   (SELECT COUNT(1) FROM T_LSGL_RK_JZRKXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS JZRKS,--寄住人口数
                   (SELECT COUNT(1) FROM T_LSGL_RK_WLHCZHK WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS WLHRKS,--未落户人口数
                   --0 AS V_LDRKYQS,
                   (SELECT COUNT(LDRKZZBH) FROM T_LSGL_LDRK_YQZX WHERE CZSJ>=V_JSKSSJ AND CZSJ<=V_JSJSSJ AND CZDWDM=LIST(I).ORGCODE AND (CZSJ <= YNJZRQ OR YNJZRQ IS NULL) ) AS V_LDRKYQS,--流动人口延期
                   
                   (SELECT COUNT(1) FROM T_LSGL_FW_JBXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS FWXXS, --房屋信息
                   (SELECT COUNT(1) FROM T_COMMON_STXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS STXXS,  --实体信息
                   (SELECT COUNT(1) FROM T_ZA_JG_JBXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS DWXXS,   --单位信息
                   (SELECT COUNT(1) FROM T_ZA_RY_CYRY WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE) AS CYRYS,   --从业人员
                   (SELECT COUNT(1) FROM T_LSGL_FW_JBXX WHERE (ZXBS IS NULL OR ZXBS='0') AND DJSJ>=V_JSKSSJ AND DJSJ<=V_JSJSSJ AND DJDWDM=LIST(I).ORGCODE AND SFCZW='1') AS CZFWS --出租房屋数
                  INTO 
                   V_ORGCODE,V_PARENTCODE,V_ORGNAME,V_LEVE,V_CZRKZS,V_LDRKZS,V_JZRKZS,V_WLHRKS,V_LDRKYQS,V_FWXXS,V_STXXS,V_DWXXS,V_CYRYS,V_CZFWS
                FROM V_COMMON_ORGANIZATION T
                WHERE ORGCODE=LIST(I).ORGCODE;
            --其他案件数量
            V_JCSJZS:=V_CZRKZS + V_LDRKZS + V_JZRKZS + V_WLHRKS + V_FWXXS + V_STXXS + V_DWXXS + V_CYRYS + V_CZFWS + ROUND((V_LDRKYQS/10),0);
            
            --出租房屋巡查数量
            SELECT COUNT(1) INTO V_CZFWXCS
            FROM (
                 SELECT DISTINCT FWID,DJDWDM 
                 FROM T_LSGL_FW_CZWXCDJ
                 WHERE DJDWDM=LIST(I).ORGCODE
                       AND DJSJ>=V_JSKSSJ
                       AND DJSJ<=V_JSJSSJ
            );
            
            SELECT COUNT(1) INTO V_RECORD FROM T_KHKP_JCSJCJSLTJ WHERE JWQDM=LIST(I).ORGCODE AND TJYF=V_TJYF AND JSJD = V_JSJD_1;
            
            -- 查询警务区的所属类别
            SELECT JWQFL INTO V_JWQFL FROM T_COMMON_ORGANIZATION_SJJS WHERE ORGCODE = LIST(I).ORGCODE;
            
            IF V_RECORD <= 0 THEN
               INSERT INTO T_KHKP_JCSJCJSLTJ
                (ID, KSSJ, JSSJ, JWQDM, JWQMC, JCSJZS, CZRKZS, JZRKZS, LDRKZS, LDRKYQS, WLHRKS, FWXXS, STXXS, DWXXS, CYRYS, CZFWS, TJSJ, TJYF, LEVE,JSJD, JWQFL,CZFWXCS)
              VALUES
                (SEQ_COMMON.NEXTVAL, V_JSKSSJ_1, V_JSJSSJ_1, LIST(I).ORGCODE, LIST(I).ORGNAME, V_JCSJZS, V_CZRKZS, V_JZRKZS, V_LDRKZS, ROUND((V_LDRKYQS/10),0)/*V_LDRKYQS*/, V_WLHRKS, V_FWXXS, V_STXXS, V_DWXXS, V_CYRYS, V_CZFWS, SYSDATE, V_TJYF, V_LEVE,V_JSJD_1, V_JWQFL,V_CZFWXCS);

            ELSE
               UPDATE T_KHKP_JCSJCJSLTJ
               SET 
                   KSSJ = V_JSKSSJ_1,
                   JSSJ = V_JSJSSJ_1,
                   JWQDM = LIST(I).ORGCODE,
                   JWQMC = LIST(I).ORGNAME,
                   JCSJZS = V_JCSJZS,
                   CZRKZS = V_CZRKZS,
                   JZRKZS = V_JZRKZS,
                   LDRKZS = V_LDRKZS,
                   LDRKYQS = V_LDRKYQS,
                   WLHRKS = V_WLHRKS,
                   FWXXS = V_FWXXS,
                   STXXS = V_STXXS,
                   DWXXS = V_DWXXS,
                   CYRYS = V_CYRYS,
                   CZFWS = V_CZFWS,
                   TJSJ = SYSDATE,
                   JWQFL = V_JWQFL,
                   CZFWXCS = V_CZFWXCS
               WHERE JWQDM = LIST(I).ORGCODE AND TJYF=V_TJYF AND JSJD = V_JSJD_1;
            END IF;
            EXCEPTION WHEN OTHERS THEN
               V_ERROR:=SQLERRM;
        END;
        COMMIT;
    END LOOP;
  END LOOP;
  CLOSE CUR_LIST;
END P_KHKP_EXECJCSJCJTJ;
/