CREATE OR REPLACE VIEW V_LSGL_LDRK_FWGL AS
SELECT C.RYBH,
      C.XM,
      C.XMPY,
      C.SFZH,
      C.XB,
      C.GJ,
      C.MZ,
      C.CSRQ,
      C.BMCH,
      C.BYZK,
      C.YWM,
      C.WHCD,
      C.ZJZL,
      C.ZJHM,
      C.ZZMM,
      C.HYZK,
      C.SG,
      C.XX,
      C.ZZXY,
      C.ZC,
      C.LXDH,
      C.FWCS,
      C.ZYDM,
      C.ZW,
      C.SF,
      C.JG,
      C.RYSX,
      '2' AS RYLB,
      C.HJDQH,
      C.HJDXZ,
      C.ZZBH,
      C.ZZZBH,
      C.HH,
      C.YHZGX,
      C.LBDRQ,
      C.ZZZQFRQ,
      C.ZZZYXQJZRQ,
      C.XFWCS,
      C.ZZSY,
      C.ZZDQH,
      C.ZZDXZ,
      C.CZBS,
      C.CZDWDM,
      C.CZDWMC,
      C.CZSJ,
      C.CZRXM,
      C.DJDWDM,
      C.DJDWMC,
      C.DJRXM,
      C.DJSJ,
      C.ZRDWDM,
      C.ZRDWMC,
      C.ZRMJXM,
      C.ZRMJJH,
      C.ZRMJLXDH,
      C.XCSZY,
      C.SSGAJGJGDM,
      C.SSGAJGJGMC,
      C.SSPCSDM,
      C.SSPCSMC,
      C.ZZCS,
      C.ZXBS,
      C.ZXSJ,
      C.ZXYY,
      C.ZAGLZRRXM,
      C.ZAGLZRRSFZH,
      C.GZGX,
      C.FHBH,
      C.BZ,
      C.HDQK,
      C.HJDLX,
      C.NJZQX,
      C.BMZW,
      C.SFZHBX,
      C.SFJKZM,
      C.SFJHSY,
      C.NJZRQ,
      C.RKFWGLID,
      FW.FWID,
      FW.DZID,
      FW.FWMC,
      FW.SFCZW,
      FW.HZSFZH AS FZSFZH,
      FW.HZXM AS FZXM,
      F_GET_DZMC(FW.DZID) AS DZMC
FROM V_LSGL_RK_LDRK C LEFT JOIN T_LSGL_RKFW_GL GL ON C.RKFWGLID=GL.RKFWGLID
     LEFT JOIN T_LSGL_FW_JBXX FW ON FW.FWID=GL.FWID
      LEFT JOIN T_COMMON_DZXX DZ ON DZ.DZID=GL.DZID;

      
-- Add/modify columns 
alter table T_LSGL_CZFW_JBXX add XGSJ date;
-- Add comments to the columns 
comment on column T_LSGL_CZFW_JBXX.XGSJ
  is '修改时间';
      
-- Add/modify columns 
alter table T_LSGL_CZFW_JBXX modify XGSJ default sysdate;