CREATE OR REPLACE FUNCTION F_GET_ZDRYCOUNT(V_CODE VARCHAR2)
--重点人员
 RETURN NUMBER AS
  V_LV     VARCHAR2(2);
  V_NUMBER NUMBER;
BEGIN
  V_LV := F_GET_DWLEVE(V_CODE);
  IF V_LV>0 AND V_LV<5 THEN
     SELECT COUNT(1) INTO V_NUMBER
     FROM T_LSGL_RK_JBXX RK, T_ZDRY_GZDX ZDRY
     WHERE ZDRY.RYBH = RK.RYBH
       AND ZDRY.YXX='1'
       AND ZDRY.CXSJ IS NULL
       AND (ZDRY.SSZRDWDM LIKE SUBSTR(V_CODE, 1, 2*V_LV) || '%' OR ZDRY.GXDWDM LIKE SUBSTR(V_CODE, 1, 2*V_LV) || '%');
  
  ELSIF V_LV=5 THEN
     SELECT COUNT(1) INTO V_NUMBER
     FROM T_LSGL_RK_JBXX RK, T_ZDRY_GZDX ZDRY
     WHERE ZDRY.RYBH = RK.RYBH
       AND ZDRY.YXX='1'
       AND ZDRY.CXSJ IS NULL
       AND (ZDRY.SSZRDWDM =V_CODE OR ZDRY.GXDWDM=V_CODE);
  
  END IF;
   
  RETURN V_NUMBER;
END F_GET_ZDRYCOUNT;
/