CREATE OR REPLACE VIEW V_LSGL_RK_CZRK_ST AS
SELECT 
      '' AS RYBH,
      B.XM,
      '' XMPY,
      B.SFHM SFZH,
      B.XB,
      'CHN' GJ,
      B.MZ,
      TO_CHAR(F_CHANGE_STRTODATE(B.CSRQ,'YYYYMMDD'),'YYYY-MM-DD') AS CSRQ,
      B.CYM BMCH,
      '' BYZK,
      '' YWM,
      B.WHCD,
      '' ZJZL,
      '' ZJHM,
      '' ZZMM,
      B.HYZK,
      B.SG,
      '' XX,
      '' ZZXY,
      '' ZC,
      '' LXDH,
      B.FWCS,
      B.ZY ZYDM,
      '' ZW,
      ''SF,
      CSD JG,
      '1' AS RYLB,
      '' RYSX,
      B.ZZSSXQ HJDQH,
      B.ZZXZ HJDXZ,
      B.SSGAJGJGDM AS SSGAJGJGDM,
      B.SSGAJGMC AS SSGAJGJGMC,
      B.KC_SSSPCS AS SSPCSDM,
      B.SSPCSMC AS SSPCSMC,
      '' RYTSSX,
      '' CZRKBH,
      B.HH,
      B.HLX HKLB,
      B.YHZGX YHZGX,
      '' HKXZ,
      B.BDYY BDYY,
      B.HSQR AS BDSJ,
      B.HDQR BDQH,
      '' BDXZ,
      B.BDYY QRYY,
      TO_CHAR(B.HSQR,'YYYY-MM-DD') AS QRSJ,
      B.HDQR,
      '' HDQRXZ,
      '1' RYZT,
      '' BZ,
      B.ZZSSXQ,
      '' ZZXZ,
      B.QTZZSSXQ,
      '' QTZZXZ
  FROM T_LSGL_RK_CZRK_ST B;
