<%@page pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript" src="<c:url value='${themePath}/js/jquery-1.6.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/template/layer/layer.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/jsp/common/js/mainindex.js'/>"></script>
<script type="text/javascript" src="<c:url value='${themePath}/js/jqplugins.js'/>"></script>
<script type="text/javascript" src="<c:url value='${themePath}/js/init.js'/>"></script>