CREATE OR REPLACE FUNCTION F_GET_ZDRYLBBJMC(V_ZDRYLBBJ VARCHAR2) RETURN VARCHAR2
AS
       V_ZDRYLBBJMC VARCHAR2(300);
       V_ZDRYLBBJMCVAL VARCHAR2(300);
BEGIN
       V_ZDRYLBBJMCVAL:='';
       IF SUBSTR(V_ZDRYLBBJ,1,1) ='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='01';
          
         IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;   
       IF SUBSTR(V_ZDRYLBBJ,2,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='02';
          
          IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
          
       END IF;
       IF SUBSTR(V_ZDRYLBBJ,3,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='03';
          
          IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;
       IF SUBSTR(V_ZDRYLBBJ,4,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='04';
          
          IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;
       IF SUBSTR(V_ZDRYLBBJ,5,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='05';
          
         IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;
       IF SUBSTR(V_ZDRYLBBJ,6,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='06';
          
         IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;
       IF SUBSTR(V_ZDRYLBBJ,7,1)='1' THEN
          SELECT MC INTO  V_ZDRYLBBJMCVAL
          FROM T_COMMON_ZDRYLB 
          WHERE DM='07';
          
         IF V_ZDRYLBBJMC IS NOT NULL THEN
             V_ZDRYLBBJMC:=V_ZDRYLBBJMC||','||V_ZDRYLBBJMCVAL;
          ELSE
            V_ZDRYLBBJMC:=V_ZDRYLBBJMC||V_ZDRYLBBJMCVAL;
          END IF;
       END IF;
       RETURN V_ZDRYLBBJMC;
END;
/