create or replace view v_za_ry_cyry as
select
    cyry.cyrybh,
    cyry.rybh,
    cyry.jgbh,
    cyry.bmmc,
    cyry.gzly,
    cyry.pynx,
    cyry.zw as zwlb,
    cyry.sjhm,
    cyry.qtlxdh,
    cyry.zsqk,
    cyry.pxzh,
    cyry.pxzs,
    cyry.zdfwdxlb,
    cyry.bwcs,
    cyry.kzcs,
    cyry.zygx,
    cyry.zywt,
    cyry.jcqk,
    cyry.bz,
    cyry.zxyy,
    cyry.zxbs,
    cyry.zxrq,
    cyry.czrxm,
    cyry.czdwdm,
    to_char(cyry.czsj,'yyyy-mm-dd HH24:mi:ss') as czsj,
    cyry.czbs,
    cyry.djdwdm,
    cyry.djdwmc,
    cyry.djrxm,
    to_char(cyry.djsj,'yyyy-mm-dd HH24:mi:ss') as djsj,
    cyry.czdwmc,
    to_char(cyry.lzsj,'yyyy-mm-dd') as lzsj,
    to_char(cyry.rzsj,'yyyy-mm-dd') as rzsj,
    cyry.cyryygh,
    cyry.xzdz,
    cyry.xm,
    cyry.xb,
    cyry.sfzh,
    cyry.csrq,
    cyry.mz,
    cyry.bmch,
    cyry.sfabry,
    cyry.rkfwglid,
    (select DWMC from t_za_jg_jbxx jg where jg.jgbh=cyry.jgbh) as dwmc,
    (select hylb from t_za_jg_jbxx jg where jg.jgbh=cyry.jgbh) as hylb
from t_za_ry_cyry cyry where exists (select 1 from t_lsgl_rk_jbxx rk where rk.rybh = cyry.rybh);


CREATE OR REPLACE VIEW V_ZDRY_GZDX AS
 
SELECT JBXX.RYBH,
       JBXX.XM,
       JBXX.XMPY,
       JBXX.SFZH,
       JBXX.XB,
       JBXX.GJ,
       JBXX.MZ,
       TO_CHAR(JBXX.CSRQ,'YYYY-MM-DD') AS CSRQ,
       JBXX.BMCH,
       JBXX.BYZK,
       JBXX.YWM,
       JBXX.WHCD,
       JBXX.ZJZL,
       JBXX.ZJHM,
       JBXX.ZZMM,
       JBXX.HYZK,
       JBXX.SG,
       JBXX.XX,
       JBXX.ZZXY,
       JBXX.ZC,
       JBXX.LXDH,
       JBXX.FWCS,
       JBXX.ZYDM,
       JBXX.ZW,
       JBXX.SF,
       JBXX.JG,
       JBXX.RYSX,
       JBXX.RYLB,
       JBXX.HJDQH,
       JBXX.XZZQH,
       JBXX.HJDXZ,
       JBXX.XZZXZ,
       JBXX.sspcsdm,
       GZDX.GZDXBH,
       GZDX.DXLB,
       GZDX.DXLB AS DXLBMC,
       GZDX.SALB,
       GZDX.LADW,
       GZDX.LADWJGDM,
       GZDX.CYZK,
       GZDX.CBCLQK,
       GZDX.SSYJ,
       GZDX.YWDA,
       GZDX.DABH,
       GZDX.ZTLX,
       GZDX.XMJJZS,
       GZDX.ISCJBJ,
       GZDX.BJCJLX,
       GZDX.ISCJZW,
       GZDX.FLWSBH,
       GZDX.FLWSMC,
       GZDX.QFJG,
       GZDX.QFSJ,
       GZDX.GLLB,
       GZDX.GLFF,
       GZDX.LGRQ,
       GZDX.LGLY,
       GZDX.LGYY,
       GZDX.CGRQ,
       GZDX.CGLY,
       GZDX.LGZT,
       GZDX.ISQGQLZDRY,
       GZDX.NRBJZDRYKSJ,
       GZDX.ZDRYLBBJ,
       GZDX.ZDRYXL,
       GZDX.YXX,
       GZDX.XZSJ,
       GZDX.BJSJ,
       GZDX.CXSJ,
       GZDX.CXDW,
       GZDX.CXR,
       GZDX.DJRXM,
       GZDX.DJDWDM,
       GZDX.DJDWMC,
       GZDX.DJSJ,
       GZDX.SSZRDWDM,
       GZDX.SSZRDWMC,
       GZDX.SFRL,
       GZDX.Gxdwdm 
  FROM T_LSGL_RK_JBXX JBXX right JOIN T_ZDRY_GZDX  GZDX ON JBXX.RYBH=GZDX.RYBH
  