CREATE OR REPLACE FUNCTION F_GET_ZDRYGZDXCOUNT(V_ORGCODE VARCHAR2,V_DXLB VARCHAR2,V_ZDRYLBBJ VARCHAR2)
--重点人员对象数量
--V_DXLB 对象类别  01:重点人员 02：工作对象
--V_ZDRYLBBJ重点人员对象类别
--01: 涉恐人员,02:涉稳人员,03:在逃人员,04:涉毒人员,05:刑事犯罪前科人员,06:肇事肇祸精神病人,07:上访人员
RETURN NUMBER
as
       V_LEVE     NUMBER;
       V_COUNTZDRYSQL  VARCHAR2(4000);
       V_COUNTWTXXSQL  VARCHAR2(4000);
       V_ZDRYCOUNT     NUMBER;
       V_WTZDRYCOUNT   NUMBER;
       V_NUMBER    NUMBER;
BEGIN
       V_LEVE:=F_GET_DWLEVE(V_ORGCODE);
       V_COUNTZDRYSQL:='select count(1) from t_zdry_gzdx where 1=1 ';
       
       IF V_DXLB IS NOT NULL THEN
           V_COUNTZDRYSQL:=V_COUNTZDRYSQL||' AND DXLB='''||V_DXLB||'''';
       END IF;
       
       IF V_ZDRYLBBJ IS NOT NULL THEN
           V_COUNTZDRYSQL:=V_COUNTZDRYSQL||' AND SUBSTR(ZDRYLBBJ,TO_NUMBER('''||V_ZDRYLBBJ||'''),1)=''1''';
       END IF;
       
       IF V_LEVE=5 THEN
          V_COUNTZDRYSQL:= V_COUNTZDRYSQL||' AND SSZRDWDM='''||V_ORGCODE||'''';
          V_COUNTWTXXSQL:='select count(distinct SFZH) from t_zdry_wtxx where JGZT=''1'' and JGDWDM ='''||V_ORGCODE||'''';
       ELSIF V_LEVE=4 THEN
          V_COUNTZDRYSQL:=V_COUNTZDRYSQL||' AND SSZRDWDM LIKE '''||SUBSTR(V_ORGCODE,1,8)||'%'||'''';  
       ELSIF V_LEVE=3 THEN
          V_COUNTZDRYSQL:=V_COUNTZDRYSQL||' AND SSZRDWDM LIKE '''||SUBSTR(V_ORGCODE,1,6)||'%'||'''';  
       ELSIF V_LEVE=2 THEN
          V_COUNTZDRYSQL:=V_COUNTZDRYSQL||' AND SSZRDWDM LIKE '''||SUBSTR(V_ORGCODE,1,4)||'%'||'''';  
       END IF;
       
       IF V_COUNTZDRYSQL IS NOT NULL THEN
          EXECUTE IMMEDIATE V_COUNTZDRYSQL INTO V_ZDRYCOUNT;
       ELSE
          V_ZDRYCOUNT:=0;
       END IF;
       IF V_WTZDRYCOUNT IS NOT NULL THEN
          EXECUTE IMMEDIATE V_COUNTWTXXSQL INTO V_WTZDRYCOUNT;
       ELSE
          V_WTZDRYCOUNT:=0;
       END IF;
       V_NUMBER:=V_ZDRYCOUNT + V_WTZDRYCOUNT; 
       RETURN V_NUMBER;
END F_GET_ZDRYGZDXCOUNT;
/